### ISSUE TITLE
problem with code blocks in html 

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/fontdocs#1]
Given a markdown codeblock such as:

    ```
        smith distclean
        smith configure
        smith build
    ````
Pandoc used to generate HTML similar to:

```
    <pre><code>        smith distclean
        smith configure
        smith build
        smith alltests</code></pre>
```

Note there are _eight_ spaces  at the start of each line: four are from the indent in the markdown itself and the additional four are from our `filter-html.lua` filter that includes the following:

```
function CodeBlock(el)
  el.text = string.gsub(el.text, "(.+)", "    %0")
  return el
end
```

which intentionally adds an extra 4 spaces to the start of every line in a codeblock.

Some time between 13-Dec-2023 and 21-Jun-2024 Pandoc started wrapping lines in the html and the result is quite different (and not what we want):

```
    <pre><code>        smith distclean
    smith configure
    smith build
    smith alltests</code></pre>
```

in which only the first line of the codeblock has 8 spaces, the remaining all have 4 — apparently the lua function now gets used only once per codeblock rather than once for every line in the codeblock. 

This results in the lines being wonky:

![image](https://github.com/user-attachments/assets/7eff6b36-a86e-4497-83c7-843dd61604b3)

Unless someone wants to figure out how to work around the change in Pandoc, I suspect the easiest thing to do is just remove that bit of our .lua filter.

**Comment by jvgaultney** [comment]
I'd agree - feel free to do that

**Comment by bobh0303** [comment]
Same problem in both html and pdf results, so both filters need changing.
